### ISSUE TITLE
#TK01: DOCUMENTO IEEE830.-Introducción, propósito, alcance y limitaciones del proyecto. Definiciones, acrónimos y abreviaturas. Referencias. Resumen. 

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadMobile/Mercado-Libro-Mobile#1]
**#US01: Como desarrollador de software, quiero tener acceso a un documento detallado de especificaciones de requisitos (IEEE 830) para comprender claramente lo que el sistema debe hacer y asegurarme de que el código que desarrollo cumpla con las expectativas del cliente.**
_Criterios de Aceptación:_
1. El documento de especificaciones de requisitos debe estar completo y cubrir todos los aspectos relevantes del sistema, incluyendo funcionalidades, interfaces, restricciones, y estándares aplicables.
2. El documento debe ser claro y comprensible, utilizando un lenguaje no ambiguo, de manera que cualquier miembro del equipo de desarrollo pueda interpretarlo de la misma forma.
3. Debe incluir ejemplos o diagramas que ayuden a ilustrar los requisitos críticos del sistema.
4. Todos los requisitos funcionales y no funcionales deben estar debidamente priorizados según la importancia para el cliente o usuario final.
5. El documento debe estar aprobado por el cliente o stakeholder antes de ser utilizado para el desarrollo.
6. Debe estar accesible en un repositorio centralizado al que los desarrolladores puedan acceder en cualquier momento durante el proceso de desarrollo.

**Comment by ldlmarcelo** [comment]
1. Introducción
Mercadolibro es una aplicación móvil nativa diseñada como la versión móvil de su ecommerce web, especializada en la venta de libros. Esta aplicación tiene como objetivo ofrecer a los usuarios una experiencia sencilla, accesible y eficiente para explorar, seleccionar y comprar libros desde sus dispositivos móviles. El presente documento especifica los requisitos para el desarrollo del Producto Mínimo Viable (MVP) de Mercadolibro, detallando las funcionalidades esenciales, requisitos no funcionales, limitaciones y otros aspectos clave que guiarán la creación de esta aplicación.

El MVP de Mercadolibro se centrará en proporcionar las funcionalidades básicas que permitan a los usuarios registrarse, iniciar sesión, navegar por una galería de libros y realizar compras a través de un carrito. La aplicación será desarrollada utilizando Android Studio y Java, asegurando compatibilidad con dispositivos Android a partir de la API 21 (Android 5.0 Lollipop). Además, se implementará un sistema de autenticación seguro mediante JWT o Auth0, y se seguirán criterios de diseño que aseguren la accesibilidad y usabilidad de la aplicación.

2. Propósito del Documento
Este documento tiene como objetivo especificar los requisitos funcionales y no funcionales del Producto Mínimo Viable (MVP) de la aplicación móvil nativa Mercadolibro. La aplicación será la versión móvil del ecommerce web de Mercadolibro, permitiendo a los usuarios registrarse, explorar una galería de libros y realizar compras.

3. Descripción General
3.1. Alcance
Mercadolibro permitirá a los usuarios buscar, visualizar y comprar libros a través de una aplicación móvil. La primera versión del producto incluirá las funcionalidades esenciales para el registro de usuarios, inicio de sesión, navegación por una galería de libros y la posibilidad de realizar compras agregando libros a un carrito.

3.2. Objetivos del Sistema

Facilitar el acceso móvil a la tienda de libros Mercadolibro.
Proveer una experiencia de usuario sencilla y segura para la compra de libros.
Implementar un MVP funcional con las características esenciales de un ecommerce de libros.
3.3. Visión General
La aplicación se desarrollará como una app nativa para Android, utilizando Android Studio y Java, con consumo de una API existente para la gestión de datos. El diseño de la app será estético y accesible, siguiendo las guías de diseño de Android.

4. Abreviaturas
RF: Requisitos Funcionales
RNF: Requisitos No Funcionales
RH: Requisitos de Hardware
RS: Requisitos de Software
PI: Plan de Implementación y Mantenimiento
CA: Criterios de Aceptación
LMT: Limitaciones
5. Limitaciones
LMT-01: La aplicación debe ser compatible solo con dispositivos Android que utilicen Android 5.0 (API 21) o superior. No se desarrollará una versión para iOS en esta etapa.
LMT-02: La persistencia de datos está limitada al uso de la API de backend existente, lo que podría restringir la capacidad de la aplicación para almacenar datos localmente en el dispositivo.
LMT-03: Las funcionalidades opcionales como "Quiénes Somos", "Landing Page" y "Contacto" se implementarán solo si el tiempo y los recursos lo permiten.
LMT-04: El MVP no incluirá un sistema de gestión de inventario o notificaciones push, lo que limita la capacidad de la aplicación para alertar a los usuarios sobre libros nuevos o cambios en el stock.
LMT-05: La integración con servicios de pago está restringida a las opciones disponibles a través de la API del backend, sin incluir métodos de pago alternativos como criptomonedas o pagos internacionales.

6. Referencias
[R01] IEEE Std 830-1998, "IEEE Recommended Practice for Software Requirements Specifications", Institute of Electrical and Electronics Engineers, 1998. Disponible en: [IEEE Xplore](https://ieeexplore.ieee.org/document/720574/figures#figures)
[R03] Documentación de Android API 21 (Lollipop): "Android Developers". Google. Disponible en: [Android Developers](https://developer.android.com/about/versions/lollipop)
[R04] Auth0 Documentation. "JWT Authentication". Auth0. Disponible en: [Auth0](https://auth0.com/docs/secure/tokens/json-web-tokens)
[R05] OWASP Foundation. "Mobile Security Testing Guide". OWASP. Disponible en: [OWASP](https://mas.owasp.org/)
