### ISSUE TITLE
#TK: Roles de usuario

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadMobile/Mercado-Libro-Mobile#207]
Implementar autorización según perfiles y permisos de usuarios.

Registrar en la documentación los roles pensados para los usuarios de MercadoLibro y los permisos de cada uno. Aunque no apliquemos todos los perfiles, una explicación de lo pensado y aplicable a futuros desarrollos. Si se puede, agregar un flujo de usuario.

Publicar en la wiki el documento pertinente con los demás puntos referentes a ciberseguridad.

#198

**Comment by ldlmarcelo** [comment]
Roles y Permisos de Usuario en MercadoLibro
1. Nombre del Componente
Roles y Permisos de Usuario
2. Descripción
Este componente gestiona los diferentes roles de usuario en la plataforma MercadoLibro y define los permisos asociados a cada rol. Su función principal es establecer los límites y capacidades de cada usuario dentro del sistema, según su rol asignado.
3. Atributos Clave
Atributo
Descripción
Tipo
ID Rol
Identificador único para cada rol
Integer
Nombre Rol
Nombre que describe el rol (e.g., Administrador, Vendedor, Comprador, Invitado)
String
Descripción
Descripción breve del rol y sus capacidades
String
Permisos
Lista de permisos que el rol tiene dentro del sistema
Array de Permisos

4. Permisos
Los permisos definen las acciones específicas que un rol puede realizar. Estos permisos son definidos según las necesidades de la plataforma y pueden ser reutilizados por diferentes roles.
Permiso
Descripción
Gestionar usuarios
Crear, editar y eliminar usuarios dentro de la plataforma 
Publicar productos
Crear y gestionar productos a la venta




Gestionar permisos
Asignar y modificar roles y permisos de usuarios
Comprar productos
Realizar compras dentro de la plataforma
Acceder a historial
Ver historial de compras o ventas
Navegar productos
Ver productos publicados sin realizar compras

5. Relaciones
Rol - Permisos: Los roles tienen una relación de muchos-a-muchos con los permisos. Un rol puede tener varios permisos, y un permiso puede ser compartido entre varios roles.
Usuario - Rol: Cada usuario del sistema tiene asignado un rol. Un usuario puede tener un solo rol activo en un momento dado.
6. Roles Definidos
Rol
Descripción
Permisos Asociados
Administrador
Control total sobre la plataforma, incluida la gestión de usuarios
Gestionar usuarios, Gestionar permisos, Publicar productos, etc.
Vendedor
Puede gestionar sus productos y visualizar reportes de ventas
Publicar productos, Visualizar reportes, Acceder a historial
Comprador
Puede comprar productos y acceder a su historial de compras
Comprar productos, Acceder a historial
Invitado (sin logueo)
Puede navegar productos pero no tiene acceso a la compra
Navegar productos

7. Flujo de Usuario
El flujo describe cómo un usuario interactúa con el sistema basado en su rol asignado:
El usuario inicia sesión o se registra.
El sistema verifica su rol y lo redirige a la interfaz correspondiente:
Administrador: Acceso al panel de administración completo.
Vendedor: Acceso al panel de gestión de productos.
Comprador: Acceso a la tienda y al historial de compras.
Invitado: Navega por la tienda sin realizar compras.
Las acciones dentro de la plataforma están limitadas según los permisos del rol del usuario.
8. Notas para Desarrollo Futuro (actualmente solo funciona el rol comprador)
Posibilidad de agregar más roles según sea necesario (e.g., moderadores, soporte).
Flexibilidad para ajustar o añadir nuevos permisos a medida que se expanden las funcionalidades del sistema.
