### ISSUE TITLE
#US16: Desarrollo de actividad Dirección de envío

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadMobile/Mercado-Libro-Mobile#213]
Como usuario de la aplicación de venta de libros, quiero poder registrar mi dirección para asegurarme de que mi compra será enviada al lugar correcto.

Criterios de Aceptación
- Formulario de Dirección:
El usuario debe poder ingresar su dirección de entrega a través de un formulario con los siguientes campos obligatorios: calle, número, ciudad, código postal, etc.
Validación de todos los campos obligatorios antes de permitir el envío del formulario.

-Almacenamiento de la Dirección:
La dirección ingresada debe ser almacenada en la base de datos del usuario para futuros pedidos.

- Confirmación de Registro:
Después de registrar o editar una dirección, el usuario debe recibir una notificación de confirmación (mensaje emergente o snackbar).

**Comment by nahir1009** [comment]
El usuario puede ingresar los datos de su dirección (calle ,número ,ciudad, provincia) al darle a guardar datos se hace el post y se muestra en pantalla los datos indicando cules fueron y que fueron guardados.
