### ISSUE TITLE
#US17: Desarrollo de actividad Método de pago

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadMobile/Mercado-Libro-Mobile#214]
Como usuario de la aplicación de venta de libros, quiero poder registrar mi tarjeta como método de pago. 

Criterios de Aceptación
- Formulario de Registro de Tarjeta:
El usuario debe poder registrar una tarjeta mediante un formulario que incluya los siguientes campos obligatorios: número de tarjeta, nombre del titular, fecha de vencimiento, y código de seguridad (CVV).
El formulario debe validar los campos antes de permitir el envío, asegurando que la tarjeta sea válida.

-Confirmación de Registro:
Al registrar una tarjeta, el usuario debe recibir una notificación de confirmación (mensaje emergente o snackbar).

Al ser una api rudimentaria y creada solo para estos fines, no vamos a proceder con mayores verificaciones (como validar tipo de tarjeta, numero, cvv, vencimiento, etc)

**Comment by nahir1009** [comment]
creada api de pago se registra tarjeta cvv vencimiento y tipo de tarjeta .Con su respectivo formulario de validacion y imprime datos
