### ISSUE TITLE
#TK24 - Implementar mensajes de carga y feedback visual:

### ISSUE THREAD

**Issue by ldlmarcelo** [CodeSquadMobile/Mercado-Libro-Mobile#38]
Añadir un indicador de carga mientras la página de productos se está preparando para mostrarse al usuario.
Implementar feedback visual para asegurar que el usuario sepa que la redirección y carga de la página están en proceso.
#11

**Comment by IvetteJN** [comment]
Se implementó un solo mensaje de aviso en caso de que no funcione la conexión con el backend y no pueda traer la lista de libros
