### ISSUE TITLE
#TK40: Equipo de desarrollo: modificar el registro de usuario

### ISSUE THREAD

**Issue by ldlmarcelo** [CodeSquadMobile/Mercado-Libro-Mobile#49]
Modificar el registro de usuario. No debe permitir el acceso directo a la aplicación, sino dar un mensaje de éxito y solicitar el ingreso con las credenciales recién registradas

#8

**Comment by nahir1009** [comment]
Ahora al registrar al usuario,da un mensaje de exito con un alert personalizado.Y no permite el acceso hasta iniciar sección con las credenciales correctas.
