### ISSUE TITLE
#TK47: Pruebas en dispositivos Android (desde Lollipop)

### ISSUE THREAD

**Issue by nahir1009** [CodeSquadMobile/Mercado-Libro-Mobile#62]
Realizar pruebas en diferentes versiones de Android, incluyendo Lollipop (5.0), para asegurar que la aplicación se visualiza correctamente y los datos se cargan sin problemas.
#22

**Comment by ldlmarcelo** [comment]
Detalle de Casos de Prueba:
1. Verificación de redirección y carga de la página de Perfil:
   - Resultado: Exitoso
   - Evidencia: La página de perfil se cargó en 0,5 segundo después de linkear desde el menú lateral Perfil.
   - No trae datos aun del back al no estar integrado
