### ISSUE TITLE
#TK48: Pruebas de rendimiento en redes móviles

### ISSUE THREAD

**Issue by nahir1009** [CodeSquadMobile/Mercado-Libro-Mobile#63]
Evaluar el rendimiento de la app en diferentes condiciones de red (3G, 4G, Wi-Fi), asegurando que los datos personales se cargan de forma rápida y eficiente.
#22

**Comment by ldlmarcelo** [comment]
Prueba de rendimiento: 
   - Resultado: Exitoso
   - Descripción: Se probó en red Wifi y 4G no presentándose demoras en la carga.
