### ISSUE TITLE
#US08: Pantalla de contacto

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadMobile/Mercado-Libro-Mobile#72]
Como usuario de la aplicación móvil Mercadolibro, quiero acceder fácilmente a las opciones de contacto de la organización, para poder comunicarme de manera rápida y sencilla cuando tenga alguna consulta o problema.

_Criterios de Aceptación:_

- Acceso a la Pantalla de Contacto:  
Dado que el usuario abre la aplicación Mercadolibro, entonces debe tener acceso visible y rápido a la pantalla de contacto desde el menú principal o la barra de navegación.

- Campos de Contacto Claros:  
Dado que el usuario ingresa a la pantalla de contacto,  entonces debe ver claro y ordenados "Mensaje" y botón de enviar una consulta.

- Validación de los Datos: 
se validara solo que el formulario de contacto NO se envié vacío, que contenga algunos caracteres).

- Confirmación de Envío: 
Dado que el usuario envía un mensaje a la organización, entonces debe recibir una confirmación visual de que el mensaje ha sido enviado correctamente o un mensaje de error si no fue exitoso.

- Seguridad y Privacidad: 
Dado que el usuario puede enviar datos personales o privados a través de la pantalla de contacto,  entonces los datos deben transmitirse de manera segura y encriptada, garantizando la privacidad del usuario.

**Comment by Leopladom** [comment]
1. Uso de HTTPS
Ya que se esta utilizando una URL que empieza con https://, estamos asegurándonos de que la transmisión de datos se realice de manera segura y cifrada a través de HTTPS, lo cual ya es un gran paso para garantizar la privacidad. No se necesita cambiar nada en el backend si este ya soporta HTTPS, lo cual es el caso en nuestro código.

2. Encriptación en el lado del cliente
Dado que el tráfico ya está protegido por HTTPS, encriptar los datos en el lado del cliente podría no ser necesario y, en muchos casos, no es recomendable sin coordinación con el backend. Si encriptamos manualmente los datos antes de enviarlos y el backend no está preparado para desencriptarlos, fallará la comunicación. La encriptación adicional debe estar coordinada con el backend.

y como nuestro backend implementa  HTTPS ya proporciona seguridad suficiente.
