### ISSUE TITLE
#US03: Inicio de sesion / registro de usuario

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadMobile/Mercado-Libro-Mobile#8]

**Comment by IvetteJN** [comment]
Como usuario de la aplicación móvil Mercadolibro,
quiero que las opciones de inicio de sesión y registro estén fácilmente accesibles al abrir la app,
para poder acceder rápidamente a mi cuenta o crear una nueva sin tener que navegar por varias pantallas.

_Criterios de Aceptación:_

- Ubicación del inicio de sesión/registro:
Dado que el usuario abre la aplicación Mercadolibro,
Entonces debe ver las opciones de inicio de sesión y registro de usuario en la pantalla inicial, sin necesidad de desplazarse o navegar por otras pantallas.

- Visibilidad clara de los botones:
Dado que el usuario está en la pantalla inicial de la aplicación,
Entonces los botones de "Iniciar Sesión" y "Registrarse" deben ser claramente visibles y destacados, para que el usuario los identifique fácilmente.

- Flujo de navegación:
Cuando el usuario selecciona "Iniciar Sesión" o "Registrarse",
Entonces debe ser dirigido a la pantalla correspondiente, ya sea para ingresar sus credenciales o para completar el proceso de registro, sin pasos intermedios innecesarios.

- Compatibilidad y responsividad:
Dado que el usuario accede a la app desde distintos dispositivos móviles,
Entonces la pantalla inicial, junto con los botones de inicio de sesión y registro, debe adaptarse a diferentes tamaños de pantalla y resoluciones, asegurando una experiencia de usuario óptima.

-Acceso directo a la pantalla principal:
Dado que el usuario ha iniciado sesión correctamente o se ha registrado con éxito,
Entonces debe ser dirigido inmediatamente a la pantalla principal de la aplicación, evitando cualquier proceso adicional innecesario.

**Comment by nahir1009** [comment]
la  activity logín fue creada correctamente  con los siguientes criterios :
1)las opciones de inicio de sesión y registro están fácilmente accesibles al abrir la app.Fue definida como pantalla principal antes de poder acceder a la app
2)botones grandes visibles y claros para el usuario final.
3)creación de Políticas de seguridad y privacidad realizadas
4)implementación de validaciones
5)testeo de seguridad
6)implementación de rutas  hacia los diferentes activitys y fragments tanto del botón iniciar sesión  como del text políticas de seguridad y privacidad.
7)diseño adaptado a los diferentes dispositivos Android (responsive).
